language: node_js
node_js: node
cache:
directories:
- node_modules
script:
- npm test
env:
- CI=true

before_deploy:
- npm install netlify-cli -g
- npm run build

deploy:
provider: script
script: netlify deploy -s $3ac74fe7-5c10-4cab-b836-6b17d8687dc9 -t $d24c7ae54e860afb696f2d8d5354a94debaed2ced5926211839796775aee7b43 -p ./build
skip_cleanup: true
on:
branch: master
